### PR TITLE
Adding support for the no flash mode

### PR DESCRIPTION
**Pull request by GorgonMeducer**
The open-source community has asked for support for no-flash mode in the RP2xxxx-DFP.

### CODE REVIEW

**Comment by will-v-pi** [comment]
@GorgonMeducer It looks like you missed the no_flash linker script file - could you add that, and then I'll give it a test and merge it?

**Comment by GorgonMeducer** [comment]
Emm... It is strange... I thought I had added it. Sorry
No worries. I will add it and let you know.

**Comment by GorgonMeducer** [comment]
It appears that the whole Device folder was ignored.
I update the .gitignore and add the missing sct file.

**Comment by GorgonMeducer** [comment]
@will-v-pi 
It appears that the whole Device folder was ignored.
I update the .gitignore and add the missing sct file.

Thank you.

**Comment by GorgonMeducer** [comment]
@will-v-pi Any updates about this?

**Comment by will-v-pi** [comment]
Thanks, this works great - the steps I took to use it were

- Open Options for Target, select Linker tab, and change Scatter File to rp2040_no_flash.sct
- Under the C/C++ (AC6) tab add the define PICO_NO_FLASH=1

I'll have a look into adding a no flash example, but for now just putting the steps here for reference

**Pull request merged**
